-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.application_customers (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  application_id uuid NOT NULL,
  customer_id uuid NOT NULL,
  role text NOT NULL,
  sequence integer,
  ownership_percentage numeric,
  created_at timestamp without time zone NOT NULL DEFAULT now(),
  created_by uuid,
  organization_id uuid,
  will_occupy_property boolean DEFAULT true,
  will_be_on_title boolean DEFAULT true,
  credit_type text DEFAULT 'individual'::text,
  invite_status text DEFAULT 'pending'::text,
  invited_at timestamp without time zone,
  accepted_at timestamp without time zone,
  econsent_given boolean DEFAULT false,
  econsent_given_at timestamp without time zone,
  econsent_ip_address text,
  CONSTRAINT application_customers_pkey PRIMARY KEY (id),
  CONSTRAINT application_customers_application_id_applications_id_fk FOREIGN KEY (application_id) REFERENCES public.applications(id),
  CONSTRAINT application_customers_customer_id_customers_id_fk FOREIGN KEY (customer_id) REFERENCES public.customers(id),
  CONSTRAINT application_customers_created_by_users_id_fk FOREIGN KEY (created_by) REFERENCES public.users(id),
  CONSTRAINT application_customers_organization_id_fk FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.application_events (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  application_id uuid NOT NULL,
  event_type text NOT NULL,
  from_status text,
  to_status text,
  from_stage text,
  to_stage text,
  user_id uuid,
  source text,
  metadata jsonb,
  created_at timestamp without time zone NOT NULL DEFAULT now(),
  organization_id uuid,
  CONSTRAINT application_events_pkey PRIMARY KEY (id),
  CONSTRAINT application_events_application_id_applications_id_fk FOREIGN KEY (application_id) REFERENCES public.applications(id),
  CONSTRAINT application_events_user_id_users_id_fk FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT application_events_organization_id_fk FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.applications (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid,
  property_id uuid,
  loan_product_id uuid NOT NULL,
  title text,
  loan_amount numeric,
  occupancy_type text,
  status text NOT NULL,
  stage text,
  assigned_to uuid,
  key_information jsonb,
  decision_result jsonb,
  created_at timestamp without time zone NOT NULL DEFAULT now(),
  updated_at timestamp without time zone NOT NULL DEFAULT now(),
  submitted_at timestamp without time zone,
  funded_at timestamp without time zone,
  application_number text UNIQUE,
  primary_customer_id uuid,
  CONSTRAINT applications_pkey PRIMARY KEY (id),
  CONSTRAINT applications_organization_id_organizations_id_fk FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT applications_property_id_properties_id_fk FOREIGN KEY (property_id) REFERENCES public.properties(id),
  CONSTRAINT applications_loan_product_id_loan_products_id_fk FOREIGN KEY (loan_product_id) REFERENCES public.loan_products(id),
  CONSTRAINT applications_assigned_to_users_id_fk FOREIGN KEY (assigned_to) REFERENCES public.users(id),
  CONSTRAINT applications_primary_customer_id_fkey FOREIGN KEY (primary_customer_id) REFERENCES public.customers(id)
);
CREATE TABLE public.asset_ownership (
  asset_id uuid NOT NULL,
  customer_id uuid NOT NULL,
  ownership_percentage numeric DEFAULT 100.00,
  ownership_role text DEFAULT 'owner'::text,
  CONSTRAINT asset_ownership_pkey PRIMARY KEY (asset_id, customer_id),
  CONSTRAINT asset_ownership_asset_id_assets_id_fk FOREIGN KEY (asset_id) REFERENCES public.assets(id),
  CONSTRAINT asset_ownership_customer_id_customers_id_fk FOREIGN KEY (customer_id) REFERENCES public.customers(id)
);
CREATE TABLE public.assets (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid,
  application_id uuid NOT NULL,
  asset_category text NOT NULL,
  asset_type text NOT NULL,
  institution_name text,
  account_number text,
  cash_or_market_value numeric NOT NULL,
  is_gift_or_grant boolean DEFAULT false,
  gift_type text,
  gift_source text,
  gift_deposited_status text,
  verification_status text DEFAULT 'not_verified'::text,
  verified_value numeric,
  description text,
  created_at timestamp without time zone NOT NULL DEFAULT now(),
  updated_at timestamp without time zone NOT NULL DEFAULT now(),
  CONSTRAINT assets_pkey PRIMARY KEY (id),
  CONSTRAINT assets_organization_id_organizations_id_fk FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT assets_application_id_applications_id_fk FOREIGN KEY (application_id) REFERENCES public.applications(id)
);
CREATE TABLE public.communications (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid,
  application_id uuid,
  customer_id uuid,
  communication_type text NOT NULL,
  direction text NOT NULL,
  channel text,
  subject text,
  content text,
  initiated_by uuid,
  external_id text,
  metadata jsonb,
  created_at timestamp without time zone NOT NULL DEFAULT now(),
  CONSTRAINT communications_pkey PRIMARY KEY (id),
  CONSTRAINT communications_organization_id_organizations_id_fk FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT communications_application_id_applications_id_fk FOREIGN KEY (application_id) REFERENCES public.applications(id),
  CONSTRAINT communications_customer_id_customers_id_fk FOREIGN KEY (customer_id) REFERENCES public.customers(id),
  CONSTRAINT communications_initiated_by_users_id_fk FOREIGN KEY (initiated_by) REFERENCES public.users(id)
);
CREATE TABLE public.customers (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid,
  customer_type text NOT NULL,
  first_name text,
  last_name text,
  company_name text,
  email text,
  phone text,
  addresses jsonb,
  key_information jsonb,
  ssn_encrypted text,
  date_of_birth date,
  created_at timestamp without time zone NOT NULL DEFAULT now(),
  updated_at timestamp without time zone NOT NULL DEFAULT now(),
  middle_name text,
  suffix text,
  citizenship_type text,
  phone_home text,
  phone_cell text,
  phone_work text,
  phone_work_ext text,
  marital_status text,
  dependent_count integer DEFAULT 0,
  dependent_ages text,
  alternate_names jsonb,
  portal_user_id uuid,
  auth_user_id uuid,
  CONSTRAINT customers_pkey PRIMARY KEY (id),
  CONSTRAINT customers_organization_id_organizations_id_fk FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT customers_auth_user_id_fkey FOREIGN KEY (auth_user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.declarations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid,
  customer_id uuid NOT NULL,
  application_id uuid NOT NULL,
  will_occupy_as_primary boolean,
  have_ownership_interest_last_3_years boolean,
  property_type_if_owned text,
  title_holding_method text,
  is_family_relationship_with_seller boolean,
  have_undisclosed_borrowed_funds boolean,
  undisclosed_borrowed_amount numeric,
  have_undisclosed_mortgage_application boolean,
  have_undisclosed_credit_application boolean,
  have_priority_liens boolean,
  have_cosigned_obligations boolean,
  have_outstanding_judgments boolean,
  are_delinquent_on_federal_debt boolean,
  is_party_to_lawsuit boolean,
  have_deed_in_lieu boolean,
  have_short_sale boolean,
  have_foreclosure boolean,
  have_bankruptcy boolean,
  bankruptcy_chapter jsonb,
  explanations jsonb,
  created_at timestamp without time zone NOT NULL DEFAULT now(),
  updated_at timestamp without time zone NOT NULL DEFAULT now(),
  CONSTRAINT declarations_pkey PRIMARY KEY (id),
  CONSTRAINT declarations_organization_id_organizations_id_fk FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT declarations_customer_id_customers_id_fk FOREIGN KEY (customer_id) REFERENCES public.customers(id),
  CONSTRAINT declarations_application_id_applications_id_fk FOREIGN KEY (application_id) REFERENCES public.applications(id)
);
CREATE TABLE public.demographics (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid,
  customer_id uuid NOT NULL,
  application_id uuid NOT NULL,
  collection_method text NOT NULL,
  declined_to_provide boolean DEFAULT false,
  ethnicity jsonb,
  ethnicity_other_description text,
  race jsonb,
  race_tribe_name text,
  race_other_asian text,
  race_other_pacific_islander text,
  sex text,
  observed_ethnicity jsonb,
  observed_race jsonb,
  observed_sex text,
  created_at timestamp without time zone NOT NULL DEFAULT now(),
  updated_at timestamp without time zone NOT NULL DEFAULT now(),
  CONSTRAINT demographics_pkey PRIMARY KEY (id),
  CONSTRAINT demographics_organization_id_organizations_id_fk FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT demographics_customer_id_customers_id_fk FOREIGN KEY (customer_id) REFERENCES public.customers(id),
  CONSTRAINT demographics_application_id_applications_id_fk FOREIGN KEY (application_id) REFERENCES public.applications(id)
);
CREATE TABLE public.documents (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid,
  application_id uuid NOT NULL,
  customer_id uuid,
  document_type text NOT NULL,
  file_name text NOT NULL,
  file_path text NOT NULL,
  file_size integer,
  mime_type text,
  status text DEFAULT 'pending'::text,
  reviewed_by uuid,
  reviewed_at timestamp without time zone,
  rejection_reason text,
  period_start date,
  period_end date,
  year integer,
  uploaded_by uuid,
  created_at timestamp without time zone NOT NULL DEFAULT now(),
  updated_at timestamp without time zone NOT NULL DEFAULT now(),
  CONSTRAINT documents_pkey PRIMARY KEY (id),
  CONSTRAINT documents_organization_id_organizations_id_fk FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT documents_application_id_applications_id_fk FOREIGN KEY (application_id) REFERENCES public.applications(id),
  CONSTRAINT documents_customer_id_customers_id_fk FOREIGN KEY (customer_id) REFERENCES public.customers(id),
  CONSTRAINT documents_reviewed_by_users_id_fk FOREIGN KEY (reviewed_by) REFERENCES public.users(id),
  CONSTRAINT documents_uploaded_by_users_id_fk FOREIGN KEY (uploaded_by) REFERENCES public.users(id)
);
CREATE TABLE public.employments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid,
  customer_id uuid NOT NULL,
  application_id uuid NOT NULL,
  employment_type text NOT NULL,
  is_current boolean DEFAULT true,
  employer_name text NOT NULL,
  employer_phone text,
  employer_street_address text,
  employer_unit text,
  employer_city text,
  employer_state text,
  employer_zip_code text,
  position_title text,
  start_date date NOT NULL,
  end_date date,
  years_in_profession integer,
  months_in_profession integer,
  is_self_employed boolean DEFAULT false,
  ownership_percentage text,
  self_employed_monthly_income numeric,
  is_employed_by_family boolean DEFAULT false,
  is_party_to_transaction boolean DEFAULT false,
  created_at timestamp without time zone NOT NULL DEFAULT now(),
  updated_at timestamp without time zone NOT NULL DEFAULT now(),
  CONSTRAINT employments_pkey PRIMARY KEY (id),
  CONSTRAINT employments_organization_id_organizations_id_fk FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT employments_customer_id_customers_id_fk FOREIGN KEY (customer_id) REFERENCES public.customers(id),
  CONSTRAINT employments_application_id_applications_id_fk FOREIGN KEY (application_id) REFERENCES public.applications(id)
);
CREATE TABLE public.gift_funds (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid,
  application_id uuid NOT NULL,
  customer_id uuid NOT NULL,
  donor_name text NOT NULL,
  donor_relationship text,
  gift_amount numeric NOT NULL,
  gift_date date,
  gift_letter_received boolean DEFAULT false,
  gift_letter_document_id uuid,
  deposited boolean DEFAULT false,
  deposit_date date,
  deposit_account text,
  created_at timestamp without time zone NOT NULL DEFAULT now(),
  updated_at timestamp without time zone NOT NULL DEFAULT now(),
  CONSTRAINT gift_funds_pkey PRIMARY KEY (id),
  CONSTRAINT gift_funds_organization_id_organizations_id_fk FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT gift_funds_application_id_applications_id_fk FOREIGN KEY (application_id) REFERENCES public.applications(id),
  CONSTRAINT gift_funds_customer_id_customers_id_fk FOREIGN KEY (customer_id) REFERENCES public.customers(id),
  CONSTRAINT gift_funds_gift_letter_document_id_documents_id_fk FOREIGN KEY (gift_letter_document_id) REFERENCES public.documents(id)
);
CREATE TABLE public.incomes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid,
  customer_id uuid NOT NULL,
  application_id uuid NOT NULL,
  employment_id uuid,
  income_source text NOT NULL,
  income_type text NOT NULL,
  monthly_amount numeric NOT NULL,
  include_in_qualification boolean DEFAULT true,
  verification_status text DEFAULT 'not_verified'::text,
  verified_amount numeric,
  description text,
  created_at timestamp without time zone NOT NULL DEFAULT now(),
  updated_at timestamp without time zone NOT NULL DEFAULT now(),
  CONSTRAINT incomes_pkey PRIMARY KEY (id),
  CONSTRAINT incomes_organization_id_organizations_id_fk FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT incomes_customer_id_customers_id_fk FOREIGN KEY (customer_id) REFERENCES public.customers(id),
  CONSTRAINT incomes_application_id_applications_id_fk FOREIGN KEY (application_id) REFERENCES public.applications(id),
  CONSTRAINT incomes_employment_id_employments_id_fk FOREIGN KEY (employment_id) REFERENCES public.employments(id)
);
CREATE TABLE public.invitation_tokens (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  application_customer_id uuid NOT NULL,
  token text NOT NULL UNIQUE,
  expires_at timestamp with time zone NOT NULL,
  used_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT invitation_tokens_pkey PRIMARY KEY (id),
  CONSTRAINT invitation_tokens_application_customer_id_fkey FOREIGN KEY (application_customer_id) REFERENCES public.application_customers(id)
);
CREATE TABLE public.liabilities (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid,
  application_id uuid NOT NULL,
  liability_type text NOT NULL,
  creditor_name text,
  account_number text,
  unpaid_balance numeric,
  monthly_payment numeric NOT NULL,
  months_remaining integer,
  to_be_paid_off_at_closing boolean DEFAULT false,
  will_be_subordinated boolean DEFAULT false,
  exclude_from_dti boolean DEFAULT false,
  exclusion_reason text,
  description text,
  created_at timestamp without time zone NOT NULL DEFAULT now(),
  updated_at timestamp without time zone NOT NULL DEFAULT now(),
  CONSTRAINT liabilities_pkey PRIMARY KEY (id),
  CONSTRAINT liabilities_organization_id_organizations_id_fk FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT liabilities_application_id_applications_id_fk FOREIGN KEY (application_id) REFERENCES public.applications(id)
);
CREATE TABLE public.liability_ownership (
  liability_id uuid NOT NULL,
  customer_id uuid NOT NULL,
  ownership_role text DEFAULT 'primary_obligor'::text,
  is_excluded boolean DEFAULT false,
  exclusion_reason text,
  CONSTRAINT liability_ownership_pkey PRIMARY KEY (customer_id, liability_id),
  CONSTRAINT liability_ownership_liability_id_liabilities_id_fk FOREIGN KEY (liability_id) REFERENCES public.liabilities(id),
  CONSTRAINT liability_ownership_customer_id_customers_id_fk FOREIGN KEY (customer_id) REFERENCES public.customers(id)
);
CREATE TABLE public.loan_products (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid,
  name text NOT NULL,
  product_type text,
  country_code text,
  customer_type text,
  template jsonb,
  is_active boolean,
  created_at timestamp without time zone NOT NULL DEFAULT now(),
  updated_at timestamp without time zone NOT NULL DEFAULT now(),
  CONSTRAINT loan_products_pkey PRIMARY KEY (id),
  CONSTRAINT loan_products_organization_id_organizations_id_fk FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.notes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid,
  application_id uuid,
  customer_id uuid,
  content text NOT NULL,
  author_id uuid,
  created_at timestamp without time zone NOT NULL DEFAULT now(),
  CONSTRAINT notes_pkey PRIMARY KEY (id),
  CONSTRAINT notes_organization_id_organizations_id_fk FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT notes_application_id_applications_id_fk FOREIGN KEY (application_id) REFERENCES public.applications(id),
  CONSTRAINT notes_customer_id_customers_id_fk FOREIGN KEY (customer_id) REFERENCES public.customers(id),
  CONSTRAINT notes_author_id_users_id_fk FOREIGN KEY (author_id) REFERENCES public.users(id)
);
CREATE TABLE public.organizations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  slug text NOT NULL UNIQUE,
  settings jsonb,
  billing_status text DEFAULT 'trial'::text,
  stripe_customer_id text,
  created_at timestamp without time zone NOT NULL DEFAULT now(),
  updated_at timestamp without time zone NOT NULL DEFAULT now(),
  CONSTRAINT organizations_pkey PRIMARY KEY (id)
);
CREATE TABLE public.properties (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid,
  address jsonb,
  country_code text,
  property_type text,
  year_built integer,
  square_feet integer,
  bedrooms integer,
  bathrooms numeric,
  appraised_value numeric,
  purchase_price numeric,
  metadata jsonb,
  created_at timestamp without time zone NOT NULL DEFAULT now(),
  updated_at timestamp without time zone NOT NULL DEFAULT now(),
  CONSTRAINT properties_pkey PRIMARY KEY (id),
  CONSTRAINT properties_organization_id_organizations_id_fk FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.real_estate_owned (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid,
  customer_id uuid NOT NULL,
  application_id uuid NOT NULL,
  property_street_address text NOT NULL,
  property_unit text,
  property_city text NOT NULL,
  property_state text NOT NULL,
  property_zip_code text NOT NULL,
  property_country text DEFAULT 'US'::text,
  property_type text,
  property_value numeric,
  property_status text,
  intended_occupancy text,
  monthly_insurance_taxes_hoa numeric,
  has_mortgage boolean DEFAULT false,
  mortgage_creditor_name text,
  mortgage_account_number text,
  mortgage_monthly_payment numeric,
  mortgage_unpaid_balance numeric,
  mortgage_to_be_paid_off boolean DEFAULT false,
  mortgage_type text,
  has_heloc boolean DEFAULT false,
  heloc_credit_limit numeric,
  heloc_balance numeric,
  is_rental boolean DEFAULT false,
  monthly_rental_income numeric,
  net_rental_income numeric,
  created_at timestamp without time zone NOT NULL DEFAULT now(),
  updated_at timestamp without time zone NOT NULL DEFAULT now(),
  CONSTRAINT real_estate_owned_pkey PRIMARY KEY (id),
  CONSTRAINT real_estate_owned_organization_id_organizations_id_fk FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT real_estate_owned_customer_id_customers_id_fk FOREIGN KEY (customer_id) REFERENCES public.customers(id),
  CONSTRAINT real_estate_owned_application_id_applications_id_fk FOREIGN KEY (application_id) REFERENCES public.applications(id)
);
CREATE TABLE public.residences (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid,
  customer_id uuid NOT NULL,
  application_id uuid NOT NULL,
  residence_type text NOT NULL,
  street_address text NOT NULL,
  unit_number text,
  city text NOT NULL,
  state text NOT NULL,
  zip_code text NOT NULL,
  country text DEFAULT 'US'::text,
  move_in_date date,
  move_out_date date,
  years_at_address integer,
  months_at_address integer,
  housing_type text,
  monthly_rent numeric,
  is_mailing_address boolean DEFAULT false,
  created_at timestamp without time zone NOT NULL DEFAULT now(),
  updated_at timestamp without time zone NOT NULL DEFAULT now(),
  CONSTRAINT residences_pkey PRIMARY KEY (id),
  CONSTRAINT residences_organization_id_organizations_id_fk FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT residences_customer_id_customers_id_fk FOREIGN KEY (customer_id) REFERENCES public.customers(id),
  CONSTRAINT residences_application_id_applications_id_fk FOREIGN KEY (application_id) REFERENCES public.applications(id)
);
CREATE TABLE public.tasks (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid,
  application_id uuid,
  customer_id uuid,
  title text NOT NULL,
  description text,
  status text NOT NULL DEFAULT 'open'::text,
  priority text DEFAULT 'medium'::text,
  assignee_id uuid,
  due_date timestamp without time zone,
  completed_at timestamp without time zone,
  created_at timestamp without time zone NOT NULL DEFAULT now(),
  created_by uuid,
  CONSTRAINT tasks_pkey PRIMARY KEY (id),
  CONSTRAINT tasks_organization_id_organizations_id_fk FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT tasks_application_id_applications_id_fk FOREIGN KEY (application_id) REFERENCES public.applications(id),
  CONSTRAINT tasks_customer_id_customers_id_fk FOREIGN KEY (customer_id) REFERENCES public.customers(id),
  CONSTRAINT tasks_assignee_id_users_id_fk FOREIGN KEY (assignee_id) REFERENCES public.users(id),
  CONSTRAINT tasks_created_by_users_id_fk FOREIGN KEY (created_by) REFERENCES public.users(id)
);
CREATE TABLE public.users (
  id uuid NOT NULL,
  organization_id uuid,
  role text NOT NULL,
  first_name text,
  last_name text,
  email text NOT NULL UNIQUE,
  phone text,
  avatar_url text,
  metadata jsonb,
  created_at timestamp without time zone NOT NULL DEFAULT now(),
  updated_at timestamp without time zone NOT NULL DEFAULT now(),
  system_admin boolean NOT NULL DEFAULT false,
  CONSTRAINT users_pkey PRIMARY KEY (id),
  CONSTRAINT users_organization_id_organizations_id_fk FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);